name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name theosinstall
      run:  bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

    - name: Install dependencies
      run: make package ipa

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
